# Generated by Django 6.0.8 on 2026-08-12 21:20

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="OxTask",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("task_path", models.CharField(max_length=255)),
                ("args", models.JSONField(blank=True, default=list)),
                ("kwargs", models.JSONField(blank=True, default=dict)),
                ("queue_name", models.CharField(default="default", max_length=128)),
                ("priority", models.SmallIntegerField(default=0)),
                ("takes_context", models.BooleanField(default=False)),
                ("backend_name", models.CharField(max_length=128)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("READY", "Ready"),
                            ("RUNNING", "Running"),
                            ("FAILED", "Failed"),
                            ("SUCCESSFUL", "Successful"),
                        ],
                        default="READY",
                        max_length=10,
                    ),
                ),
                ("run_after", models.DateTimeField(blank=True, null=True)),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
                ("max_attempts", models.PositiveSmallIntegerField(default=3)),
                ("return_value", models.JSONField(blank=True, null=True)),
                ("errors", models.JSONField(blank=True, default=list)),
                ("worker_ids", models.JSONField(blank=True, default=list)),
                ("enqueued_at", models.DateTimeField()),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("last_attempted_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("locked_by", models.CharField(blank=True, max_length=64, null=True)),
                ("locked_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["status", "queue_name", "-priority", "run_after"],
                        name="ox_dequeue_idx",
                    ),
                    models.Index(fields=["status", "locked_at"], name="ox_reaper_idx"),
                ],
            },
        ),
    ]
