# Generated by Django 6.0.8 on 2026-08-13 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_ox", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OxScheduleTick",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("schedule_name", models.CharField(max_length=128)),
                ("scheduled_for", models.DateTimeField()),
                ("created_at", models.DateTimeField()),
                (
                    "task",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="schedule_ticks",
                        to="django_ox.oxtask",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("schedule_name", "scheduled_for"), name="ox_tick_uniq"
                    )
                ],
            },
        ),
    ]
