# Generated by Django 6.0.8 on 2026-08-20 12:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_ox", "0002_oxscheduletick"),
    ]

    operations = [
        migrations.AddField(
            model_name="oxtask",
            name="lease_epoch",
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="oxtask",
            name="status",
            field=models.CharField(
                choices=[
                    ("READY", "Ready"),
                    ("RUNNING", "Running"),
                    ("FAILED", "Failed"),
                    ("SUCCESSFUL", "Successful"),
                    ("LOST", "Lost"),
                ],
                default="READY",
                max_length=10,
            ),
        ),
    ]
