# Generated by Django 6.0.8 on 2026-09-11 12:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_ox", "0005_dequeue_index"),
    ]

    operations = [
        migrations.AddField(
            model_name="oxtask",
            name="lease_expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name="oxtask",
            index=models.Index(
                fields=["status", "lease_expires_at"], name="ox_reaper_expiry_idx"
            ),
        ),
    ]
